Traceback (most recent call last):
  File "D:\Documents\GitHub\MDI - Código Fonte - PDE 2031 (3)\Principal.py", line 24, in <module>
    control = Control(plan_dados = planilha, path = caminho, time = startDate);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\MDI - Código Fonte - PDE 2031 (3)\Control.py", line 62, in __init__
    self.saida_dados = SaidaDados(self.sin, self.problema, self.caminho, self.planilha, self.pastaCod, self.nomeSubs, self.isCustoRestPotHabilitado);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\MDI - Código Fonte - PDE 2031 (3)\SaidaDados.py", line 43, in __init__
    self.imprimeSaidaExpansao();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\GitHub\MDI - Código Fonte - PDE 2031 (3)\SaidaDados.py", line 280, in imprimeSaidaExpansao
    if (modelo.investHidro[hidro,per] == 1): mes_entrada = per  # no periodo que entrou atribui o periodo
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SSD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyomo\core\expr\relational_expr.py", line 331, in __bool__
    return super().__bool__()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SSD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyomo\core\expr\relational_expr.py", line 48, in __bool__
    raise PyomoException(
pyomo.common.errors.PyomoException: Cannot convert non-constant Pyomo expression (investHidro[MIRADOR,0]  ==  1) to bool.
This error is usually caused by using a Var, unit, or mutable Param in a
Boolean context such as an "if" statement, or when checking container
membership or equality. For example,
    >>> m.x = Var()
    >>> if m.x >= 1:
    ...     pass
and
    >>> m.y = Var()
    >>> if m.y in [m.x, m.y]:
    ...     pass
would both cause this exception.
